### ISSUE TITLE
Can't delete from KeyChainStore

### ISSUE THREAD

**Issue by justTreme** [omaralbeik/Stores#20]
Whenever I want to delete a value from the MultiKeyChainStore I get the error:
KeyChainStore.KeyChainError-Error 0.

This is the code im using:
```swift
do {
    try keyChainStore.removeAll()
} catch {
    print(error.localizedDescription)
}
```

**Comment by omaralbeik** [comment]
Thanks for reporting, I added more logging in v0.4.1, @justTreme could you update and share more details here again

**Comment by justTreme** [comment]
Sure. I updated to version 0.4.1 and the only thing I get printed to the console is:
keychain(-50)

**Comment by omaralbeik** [comment]
@justTreme could you please share the following info to help me investigate:
- Device
- iOS version
- Does the device have a passcode?
- How you initialized your store
- Is the device locked when performing the `removeAll()`?

**Comment by justTreme** [comment]
Can I support you with any more information?

**Comment by omaralbeik** [comment]
@justTreme I don't know why this is happening, will try to look at it in more details sometime next week.
For now, you can help me by cloning the repo and investigating the issue it if you're interested 😄

**Comment by justTreme** [comment]
Unfortunately I could not find anything. Hopefully you can find the error.
