### ISSUE TITLE
Add DooC documentation

### ISSUE THREAD

**Issue by omaralbeik** [omaralbeik/Stores#9]
Examples:
- [ComposableArchitecture](https://swiftpackageindex.com/pointfreeco/swift-composable-architecture/0.39.1/documentation/composablearchitecture)
- [RevenueCat](https://swiftpackageindex.com/RevenueCat/purchases-ios/4.10.2/documentation/revenuecat)

[More details](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/)

**Comment by DevAgani** [comment]
@omaralbeik , this can be closed right. I have checked and confirmed the `Stores` is listed https://swiftpackageindex.com/omaralbeik/Stores

**Comment by omaralbeik** [comment]
It is added indeed, but this is something else, when you go to the [docs](https://swiftpackageindex.com/omaralbeik/Stores/0.3.3/documentation/stores) you see a blank screen, unlike the examples in the description, where you see an intro and a discussion about the library.

**Comment by DevAgani** [comment]
@omaralbeik Good catch that one. i'll try to investigate why that is happening.
